### ISSUE TITLE
both dmenu scripts output the previous selection

### ISSUE THREAD

**Issue by magnetophon** [trapd00r/clipbored#6]
When I run dmenuclip or dmenurl, they output the text I selected on the previous run.
How do I troubleshoot this further?

**Comment by trapd00r** [comment]
What do you mean by "previous run"? They both work as intended for me.

**Comment by magnetophon** [comment]
I'm not sure anymore, since I wrote this 3 years ago, and I haven't used clipbored after the initial evaluation.
Maybe it's best to close the issue.
